# Alternative GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq ($(shell echo "test"), "test")
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

ifeq ($(origin CC), default)
  CC = emcc
endif
ifeq ($(origin CXX), default)
  CXX = em++
endif
ifeq ($(origin AR), default)
  AR = emar
endif
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LDDEPS +=
LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),debug)
TARGETDIR = bin
TARGET = $(TARGETDIR)/libproject.wasm
OBJDIR = bin/bin_int/Debug
DEFINES += -DGRAPHICS_API_OPENGL_ES2 -DVE_WEB -DPLATFORM_WEB -DVE_PROJECT_EXPORT -DUSE_LIBTYPE_SHARED -DVE_EDITOR -DVE_DEBUG
INCLUDES += -Isrc -I../../VEngine/src -I../../VEngine/third_party/raylib/src -I../../VEngine/third_party/glad -I../../VEngine/third_party/glm -I../../VEngine/third_party/freetype/include -I../../VEngine/third_party/nlohmann_json/include -I../../VEngine/third_party/glfw/include -I../../VEngine/third_party/flecs/include -I../../VEngine/third_party/ShapingEngine -I../../VEngine/third_party/utfcpp/source -I../../VEngine/third_party/SPIRV-Cross -I../../VEngine/third_party/SPIRV-Cross/include -I../../VEngine/third_party/imgui -I../../VEngine/third_party/rlImGui -I../../VEngine/third_party/ImGuizmo
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -fPIC -g -sUSE_PTHREADS=1 -msimd128
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -fPIC -g -std=c++20 -sUSE_PTHREADS=1 -msimd128
LIBS += -lVEngine
ALL_LDFLAGS += $(LDFLAGS) -L../../bin/Debug_emscripten_wasm32/VEngine -shared -o bin/SpaceShooter.html -sWASM=1 -sUSE_GLFW=3 --preload-file bin/data.VEData@./data.VEData -s STACK_SIZE=4194304 -sALLOW_MEMORY_GROWTH
define PREBUILDCMDS
	@echo Running prebuild commands
	cd 
	D:\VEngine/bin/Debug_windows_x86_64//VEHeaderTool/VEHeaderTool.exe p src/generated/ src/ -c VE_CLASS -e VE_ENUM -f VE_FUNCTION -p VE_PROPERTY
	rm -f bin/*.pdb
endef

else ifeq ($(config),release)
TARGETDIR = bin
TARGET = $(TARGETDIR)/libproject.wasm
OBJDIR = bin/bin_int/Release
DEFINES += -DGRAPHICS_API_OPENGL_ES2 -DVE_WEB -DPLATFORM_WEB -DVE_PROJECT_EXPORT -DUSE_LIBTYPE_SHARED -DVE_EDITOR -DVE_RELEASE
INCLUDES += -Isrc -I../../VEngine/src -I../../VEngine/third_party/raylib/src -I../../VEngine/third_party/glad -I../../VEngine/third_party/glm -I../../VEngine/third_party/freetype/include -I../../VEngine/third_party/nlohmann_json/include -I../../VEngine/third_party/glfw/include -I../../VEngine/third_party/flecs/include -I../../VEngine/third_party/ShapingEngine -I../../VEngine/third_party/utfcpp/source -I../../VEngine/third_party/SPIRV-Cross -I../../VEngine/third_party/SPIRV-Cross/include -I../../VEngine/third_party/imgui -I../../VEngine/third_party/rlImGui -I../../VEngine/third_party/ImGuizmo
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -O2 -fPIC -sUSE_PTHREADS=1 -msimd128
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -O2 -fPIC -std=c++20 -sUSE_PTHREADS=1 -msimd128
LIBS += -lVEngine
ALL_LDFLAGS += $(LDFLAGS) -L../../bin/Release_emscripten_wasm32/VEngine -shared -o bin/SpaceShooter.html -sWASM=1 -sUSE_GLFW=3 --preload-file bin/data.VEData@./data.VEData -s STACK_SIZE=4194304 -sALLOW_MEMORY_GROWTH
define PREBUILDCMDS
	@echo Running prebuild commands
	cd 
	D:\VEngine/bin/Debug_windows_x86_64//VEHeaderTool/VEHeaderTool.exe p src/generated/ src/ -c VE_CLASS -e VE_ENUM -f VE_FUNCTION -p VE_PROPERTY
	rm -f bin/*.pdb
endef

else ifeq ($(config),game_debug)
TARGETDIR = dist/Game_Debug_emscripten_wasm32/bin
TARGET = $(TARGETDIR)/SpaceShooter.wasm
OBJDIR = dist/Game_Debug_emscripten_wasm32/bin_int
DEFINES += -DGRAPHICS_API_OPENGL_ES2 -DVE_WEB -DPLATFORM_WEB -DFT2_BUILD_LIBRARY -DSPIRV_CROSS_ENABLE_GLSL -DSPIRV_CROSS_ENABLE_C_API -DSPIRV_CROSS_EXCEPTIONS_TO_ASSERTIONS -Dflecs_STATIC -DVE_DEBUG
INCLUDES += -Isrc -I../../VEngine/src -I../../VEngine/third_party/raylib/src -I../../VEngine/third_party/glad -I../../VEngine/third_party/glm -I../../VEngine/third_party/freetype/include -I../../VEngine/third_party/nlohmann_json/include -I../../VEngine/third_party/glfw/include -I../../VEngine/third_party/flecs/include -I../../VEngine/third_party/ShapingEngine -I../../VEngine/third_party/utfcpp/source -I../../VEngine/third_party/SPIRV-Cross -I../../VEngine/third_party/SPIRV-Cross/include -I../../VEAssetsPackager/src
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -g -sUSE_PTHREADS=1 -msimd128
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -g -std=c++20 -sUSE_PTHREADS=1 -msimd128
LIBS +=
ALL_LDFLAGS += $(LDFLAGS) -o dist/Game_Debug_emscripten_wasm32/bin/SpaceShooter.html -sWASM=1 -sUSE_GLFW=3 --preload-file dist/Game_Debug_emscripten_wasm32/bin/data.VEData@./data.VEData -s STACK_SIZE=4194304 -sALLOW_MEMORY_GROWTH
define PREBUILDCMDS
	@echo Running prebuild commands
	cd 
	D:\VEngine/bin/Debug_windows_x86_64//VEHeaderTool/VEHeaderTool.exe p src/generated/ src/ -c VE_CLASS -e VE_ENUM -f VE_FUNCTION -p VE_PROPERTY
endef

else ifeq ($(config),game_release)
TARGETDIR = dist/Game_Release_emscripten_wasm32/bin
TARGET = $(TARGETDIR)/SpaceShooter.wasm
OBJDIR = dist/Game_Release_emscripten_wasm32/bin_int
DEFINES += -DGRAPHICS_API_OPENGL_ES2 -DVE_WEB -DPLATFORM_WEB -DFT2_BUILD_LIBRARY -DSPIRV_CROSS_ENABLE_GLSL -DSPIRV_CROSS_ENABLE_C_API -DSPIRV_CROSS_EXCEPTIONS_TO_ASSERTIONS -Dflecs_STATIC -DVE_RELEASE
INCLUDES += -Isrc -I../../VEngine/src -I../../VEngine/third_party/raylib/src -I../../VEngine/third_party/glad -I../../VEngine/third_party/glm -I../../VEngine/third_party/freetype/include -I../../VEngine/third_party/nlohmann_json/include -I../../VEngine/third_party/glfw/include -I../../VEngine/third_party/flecs/include -I../../VEngine/third_party/ShapingEngine -I../../VEngine/third_party/utfcpp/source -I../../VEngine/third_party/SPIRV-Cross -I../../VEngine/third_party/SPIRV-Cross/include -I../../VEAssetsPackager/src
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -O2 -sUSE_PTHREADS=1 -msimd128
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -O2 -std=c++20 -sUSE_PTHREADS=1 -msimd128
LIBS +=
ALL_LDFLAGS += $(LDFLAGS) -o dist/Game_Release_emscripten_wasm32/bin/SpaceShooter.html -sWASM=1 -sUSE_GLFW=3 --preload-file dist/Game_Release_emscripten_wasm32/bin/data.VEData@./data.VEData -s STACK_SIZE=4194304 -sALLOW_MEMORY_GROWTH
define PREBUILDCMDS
	@echo Running prebuild commands
	cd 
	D:\VEngine/bin/Debug_windows_x86_64//VEHeaderTool/VEHeaderTool.exe p src/generated/ src/ -c VE_CLASS -e VE_ENUM -f VE_FUNCTION -p VE_PROPERTY
endef

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/entry_point.o
GENERATED += $(OBJDIR)/register.o
GENERATED += $(OBJDIR)/systems.o
GENERATED += $(OBJDIR)/ve_generated_editor_file1.o
GENERATED += $(OBJDIR)/ve_generated_serialization_file1.o
OBJECTS += $(OBJDIR)/entry_point.o
OBJECTS += $(OBJDIR)/register.o
OBJECTS += $(OBJDIR)/systems.o
OBJECTS += $(OBJDIR)/ve_generated_editor_file1.o
OBJECTS += $(OBJDIR)/ve_generated_serialization_file1.o

ifeq ($(config),game_debug)
GENERATED += $(OBJDIR)/autofit.o
GENERATED += $(OBJDIR)/bdf.o
GENERATED += $(OBJDIR)/cff.o
GENERATED += $(OBJDIR)/flecs.o
GENERATED += $(OBJDIR)/ftbase.o
GENERATED += $(OBJDIR)/ftbbox.o
GENERATED += $(OBJDIR)/ftbdf.o
GENERATED += $(OBJDIR)/ftbitmap.o
GENERATED += $(OBJDIR)/ftbzip2.o
GENERATED += $(OBJDIR)/ftcache.o
GENERATED += $(OBJDIR)/ftcid.o
GENERATED += $(OBJDIR)/ftdebug.o
GENERATED += $(OBJDIR)/ftfstype.o
GENERATED += $(OBJDIR)/ftgasp.o
GENERATED += $(OBJDIR)/ftglyph.o
GENERATED += $(OBJDIR)/ftgxval.o
GENERATED += $(OBJDIR)/ftgzip.o
GENERATED += $(OBJDIR)/ftinit.o
GENERATED += $(OBJDIR)/ftlzw.o
GENERATED += $(OBJDIR)/ftmm.o
GENERATED += $(OBJDIR)/ftotval.o
GENERATED += $(OBJDIR)/ftpatent.o
GENERATED += $(OBJDIR)/ftpfr.o
GENERATED += $(OBJDIR)/ftstroke.o
GENERATED += $(OBJDIR)/ftsynth.o
GENERATED += $(OBJDIR)/ftsystem.o
GENERATED += $(OBJDIR)/fttype1.o
GENERATED += $(OBJDIR)/ftwinfnt.o
GENERATED += $(OBJDIR)/pcf.o
GENERATED += $(OBJDIR)/pfr.o
GENERATED += $(OBJDIR)/psaux.o
GENERATED += $(OBJDIR)/pshinter.o
GENERATED += $(OBJDIR)/psnames.o
GENERATED += $(OBJDIR)/raster.o
GENERATED += $(OBJDIR)/raudio.o
GENERATED += $(OBJDIR)/rcore.o
GENERATED += $(OBJDIR)/rmodels.o
GENERATED += $(OBJDIR)/rshapes.o
GENERATED += $(OBJDIR)/rtext.o
GENERATED += $(OBJDIR)/rtextures.o
GENERATED += $(OBJDIR)/sdf.o
GENERATED += $(OBJDIR)/sfnt.o
GENERATED += $(OBJDIR)/smooth.o
GENERATED += $(OBJDIR)/spirv_cfg.o
GENERATED += $(OBJDIR)/spirv_cpp.o
GENERATED += $(OBJDIR)/spirv_cross.o
GENERATED += $(OBJDIR)/spirv_cross_c.o
GENERATED += $(OBJDIR)/spirv_cross_parsed_ir.o
GENERATED += $(OBJDIR)/spirv_cross_util.o
GENERATED += $(OBJDIR)/spirv_glsl.o
GENERATED += $(OBJDIR)/spirv_hlsl.o
GENERATED += $(OBJDIR)/spirv_msl.o
GENERATED += $(OBJDIR)/spirv_parser.o
GENERATED += $(OBJDIR)/spirv_reflect.o
GENERATED += $(OBJDIR)/svg.o
GENERATED += $(OBJDIR)/truetype.o
GENERATED += $(OBJDIR)/type1.o
GENERATED += $(OBJDIR)/type1cid.o
GENERATED += $(OBJDIR)/type42.o
GENERATED += $(OBJDIR)/utils.o
GENERATED += $(OBJDIR)/ve_assets_manager.o
GENERATED += $(OBJDIR)/ve_editor.o
GENERATED += $(OBJDIR)/ve_editor_elements.o
GENERATED += $(OBJDIR)/ve_engine.o
GENERATED += $(OBJDIR)/ve_flecs_os_backend.o
GENERATED += $(OBJDIR)/ve_font.o
GENERATED += $(OBJDIR)/ve_generated_editor_file.o
GENERATED += $(OBJDIR)/ve_generated_serialization_file.o
GENERATED += $(OBJDIR)/ve_input.o
GENERATED += $(OBJDIR)/ve_renderer.o
GENERATED += $(OBJDIR)/ve_scene.o
GENERATED += $(OBJDIR)/ve_scene_manager.o
GENERATED += $(OBJDIR)/ve_serialization.o
GENERATED += $(OBJDIR)/ve_systems.o
GENERATED += $(OBJDIR)/ve_utils.o
GENERATED += $(OBJDIR)/ve_win32_platform.o
GENERATED += $(OBJDIR)/ve_win32_shared_library.o
GENERATED += $(OBJDIR)/winfnt.o
OBJECTS += $(OBJDIR)/autofit.o
OBJECTS += $(OBJDIR)/bdf.o
OBJECTS += $(OBJDIR)/cff.o
OBJECTS += $(OBJDIR)/flecs.o
OBJECTS += $(OBJDIR)/ftbase.o
OBJECTS += $(OBJDIR)/ftbbox.o
OBJECTS += $(OBJDIR)/ftbdf.o
OBJECTS += $(OBJDIR)/ftbitmap.o
OBJECTS += $(OBJDIR)/ftbzip2.o
OBJECTS += $(OBJDIR)/ftcache.o
OBJECTS += $(OBJDIR)/ftcid.o
OBJECTS += $(OBJDIR)/ftdebug.o
OBJECTS += $(OBJDIR)/ftfstype.o
OBJECTS += $(OBJDIR)/ftgasp.o
OBJECTS += $(OBJDIR)/ftglyph.o
OBJECTS += $(OBJDIR)/ftgxval.o
OBJECTS += $(OBJDIR)/ftgzip.o
OBJECTS += $(OBJDIR)/ftinit.o
OBJECTS += $(OBJDIR)/ftlzw.o
OBJECTS += $(OBJDIR)/ftmm.o
OBJECTS += $(OBJDIR)/ftotval.o
OBJECTS += $(OBJDIR)/ftpatent.o
OBJECTS += $(OBJDIR)/ftpfr.o
OBJECTS += $(OBJDIR)/ftstroke.o
OBJECTS += $(OBJDIR)/ftsynth.o
OBJECTS += $(OBJDIR)/ftsystem.o
OBJECTS += $(OBJDIR)/fttype1.o
OBJECTS += $(OBJDIR)/ftwinfnt.o
OBJECTS += $(OBJDIR)/pcf.o
OBJECTS += $(OBJDIR)/pfr.o
OBJECTS += $(OBJDIR)/psaux.o
OBJECTS += $(OBJDIR)/pshinter.o
OBJECTS += $(OBJDIR)/psnames.o
OBJECTS += $(OBJDIR)/raster.o
OBJECTS += $(OBJDIR)/raudio.o
OBJECTS += $(OBJDIR)/rcore.o
OBJECTS += $(OBJDIR)/rmodels.o
OBJECTS += $(OBJDIR)/rshapes.o
OBJECTS += $(OBJDIR)/rtext.o
OBJECTS += $(OBJDIR)/rtextures.o
OBJECTS += $(OBJDIR)/sdf.o
OBJECTS += $(OBJDIR)/sfnt.o
OBJECTS += $(OBJDIR)/smooth.o
OBJECTS += $(OBJDIR)/spirv_cfg.o
OBJECTS += $(OBJDIR)/spirv_cpp.o
OBJECTS += $(OBJDIR)/spirv_cross.o
OBJECTS += $(OBJDIR)/spirv_cross_c.o
OBJECTS += $(OBJDIR)/spirv_cross_parsed_ir.o
OBJECTS += $(OBJDIR)/spirv_cross_util.o
OBJECTS += $(OBJDIR)/spirv_glsl.o
OBJECTS += $(OBJDIR)/spirv_hlsl.o
OBJECTS += $(OBJDIR)/spirv_msl.o
OBJECTS += $(OBJDIR)/spirv_parser.o
OBJECTS += $(OBJDIR)/spirv_reflect.o
OBJECTS += $(OBJDIR)/svg.o
OBJECTS += $(OBJDIR)/truetype.o
OBJECTS += $(OBJDIR)/type1.o
OBJECTS += $(OBJDIR)/type1cid.o
OBJECTS += $(OBJDIR)/type42.o
OBJECTS += $(OBJDIR)/utils.o
OBJECTS += $(OBJDIR)/ve_assets_manager.o
OBJECTS += $(OBJDIR)/ve_editor.o
OBJECTS += $(OBJDIR)/ve_editor_elements.o
OBJECTS += $(OBJDIR)/ve_engine.o
OBJECTS += $(OBJDIR)/ve_flecs_os_backend.o
OBJECTS += $(OBJDIR)/ve_font.o
OBJECTS += $(OBJDIR)/ve_generated_editor_file.o
OBJECTS += $(OBJDIR)/ve_generated_serialization_file.o
OBJECTS += $(OBJDIR)/ve_input.o
OBJECTS += $(OBJDIR)/ve_renderer.o
OBJECTS += $(OBJDIR)/ve_scene.o
OBJECTS += $(OBJDIR)/ve_scene_manager.o
OBJECTS += $(OBJDIR)/ve_serialization.o
OBJECTS += $(OBJDIR)/ve_systems.o
OBJECTS += $(OBJDIR)/ve_utils.o
OBJECTS += $(OBJDIR)/ve_win32_platform.o
OBJECTS += $(OBJDIR)/ve_win32_shared_library.o
OBJECTS += $(OBJDIR)/winfnt.o

else ifeq ($(config),game_release)
GENERATED += $(OBJDIR)/autofit.o
GENERATED += $(OBJDIR)/bdf.o
GENERATED += $(OBJDIR)/cff.o
GENERATED += $(OBJDIR)/flecs.o
GENERATED += $(OBJDIR)/ftbase.o
GENERATED += $(OBJDIR)/ftbbox.o
GENERATED += $(OBJDIR)/ftbdf.o
GENERATED += $(OBJDIR)/ftbitmap.o
GENERATED += $(OBJDIR)/ftbzip2.o
GENERATED += $(OBJDIR)/ftcache.o
GENERATED += $(OBJDIR)/ftcid.o
GENERATED += $(OBJDIR)/ftdebug.o
GENERATED += $(OBJDIR)/ftfstype.o
GENERATED += $(OBJDIR)/ftgasp.o
GENERATED += $(OBJDIR)/ftglyph.o
GENERATED += $(OBJDIR)/ftgxval.o
GENERATED += $(OBJDIR)/ftgzip.o
GENERATED += $(OBJDIR)/ftinit.o
GENERATED += $(OBJDIR)/ftlzw.o
GENERATED += $(OBJDIR)/ftmm.o
GENERATED += $(OBJDIR)/ftotval.o
GENERATED += $(OBJDIR)/ftpatent.o
GENERATED += $(OBJDIR)/ftpfr.o
GENERATED += $(OBJDIR)/ftstroke.o
GENERATED += $(OBJDIR)/ftsynth.o
GENERATED += $(OBJDIR)/ftsystem.o
GENERATED += $(OBJDIR)/fttype1.o
GENERATED += $(OBJDIR)/ftwinfnt.o
GENERATED += $(OBJDIR)/pcf.o
GENERATED += $(OBJDIR)/pfr.o
GENERATED += $(OBJDIR)/psaux.o
GENERATED += $(OBJDIR)/pshinter.o
GENERATED += $(OBJDIR)/psnames.o
GENERATED += $(OBJDIR)/raster.o
GENERATED += $(OBJDIR)/raudio.o
GENERATED += $(OBJDIR)/rcore.o
GENERATED += $(OBJDIR)/rmodels.o
GENERATED += $(OBJDIR)/rshapes.o
GENERATED += $(OBJDIR)/rtext.o
GENERATED += $(OBJDIR)/rtextures.o
GENERATED += $(OBJDIR)/sdf.o
GENERATED += $(OBJDIR)/sfnt.o
GENERATED += $(OBJDIR)/smooth.o
GENERATED += $(OBJDIR)/spirv_cfg.o
GENERATED += $(OBJDIR)/spirv_cpp.o
GENERATED += $(OBJDIR)/spirv_cross.o
GENERATED += $(OBJDIR)/spirv_cross_c.o
GENERATED += $(OBJDIR)/spirv_cross_parsed_ir.o
GENERATED += $(OBJDIR)/spirv_cross_util.o
GENERATED += $(OBJDIR)/spirv_glsl.o
GENERATED += $(OBJDIR)/spirv_hlsl.o
GENERATED += $(OBJDIR)/spirv_msl.o
GENERATED += $(OBJDIR)/spirv_parser.o
GENERATED += $(OBJDIR)/spirv_reflect.o
GENERATED += $(OBJDIR)/svg.o
GENERATED += $(OBJDIR)/truetype.o
GENERATED += $(OBJDIR)/type1.o
GENERATED += $(OBJDIR)/type1cid.o
GENERATED += $(OBJDIR)/type42.o
GENERATED += $(OBJDIR)/utils.o
GENERATED += $(OBJDIR)/ve_assets_manager.o
GENERATED += $(OBJDIR)/ve_editor.o
GENERATED += $(OBJDIR)/ve_editor_elements.o
GENERATED += $(OBJDIR)/ve_engine.o
GENERATED += $(OBJDIR)/ve_flecs_os_backend.o
GENERATED += $(OBJDIR)/ve_font.o
GENERATED += $(OBJDIR)/ve_generated_editor_file.o
GENERATED += $(OBJDIR)/ve_generated_serialization_file.o
GENERATED += $(OBJDIR)/ve_input.o
GENERATED += $(OBJDIR)/ve_renderer.o
GENERATED += $(OBJDIR)/ve_scene.o
GENERATED += $(OBJDIR)/ve_scene_manager.o
GENERATED += $(OBJDIR)/ve_serialization.o
GENERATED += $(OBJDIR)/ve_systems.o
GENERATED += $(OBJDIR)/ve_utils.o
GENERATED += $(OBJDIR)/ve_win32_platform.o
GENERATED += $(OBJDIR)/ve_win32_shared_library.o
GENERATED += $(OBJDIR)/winfnt.o
OBJECTS += $(OBJDIR)/autofit.o
OBJECTS += $(OBJDIR)/bdf.o
OBJECTS += $(OBJDIR)/cff.o
OBJECTS += $(OBJDIR)/flecs.o
OBJECTS += $(OBJDIR)/ftbase.o
OBJECTS += $(OBJDIR)/ftbbox.o
OBJECTS += $(OBJDIR)/ftbdf.o
OBJECTS += $(OBJDIR)/ftbitmap.o
OBJECTS += $(OBJDIR)/ftbzip2.o
OBJECTS += $(OBJDIR)/ftcache.o
OBJECTS += $(OBJDIR)/ftcid.o
OBJECTS += $(OBJDIR)/ftdebug.o
OBJECTS += $(OBJDIR)/ftfstype.o
OBJECTS += $(OBJDIR)/ftgasp.o
OBJECTS += $(OBJDIR)/ftglyph.o
OBJECTS += $(OBJDIR)/ftgxval.o
OBJECTS += $(OBJDIR)/ftgzip.o
OBJECTS += $(OBJDIR)/ftinit.o
OBJECTS += $(OBJDIR)/ftlzw.o
OBJECTS += $(OBJDIR)/ftmm.o
OBJECTS += $(OBJDIR)/ftotval.o
OBJECTS += $(OBJDIR)/ftpatent.o
OBJECTS += $(OBJDIR)/ftpfr.o
OBJECTS += $(OBJDIR)/ftstroke.o
OBJECTS += $(OBJDIR)/ftsynth.o
OBJECTS += $(OBJDIR)/ftsystem.o
OBJECTS += $(OBJDIR)/fttype1.o
OBJECTS += $(OBJDIR)/ftwinfnt.o
OBJECTS += $(OBJDIR)/pcf.o
OBJECTS += $(OBJDIR)/pfr.o
OBJECTS += $(OBJDIR)/psaux.o
OBJECTS += $(OBJDIR)/pshinter.o
OBJECTS += $(OBJDIR)/psnames.o
OBJECTS += $(OBJDIR)/raster.o
OBJECTS += $(OBJDIR)/raudio.o
OBJECTS += $(OBJDIR)/rcore.o
OBJECTS += $(OBJDIR)/rmodels.o
OBJECTS += $(OBJDIR)/rshapes.o
OBJECTS += $(OBJDIR)/rtext.o
OBJECTS += $(OBJDIR)/rtextures.o
OBJECTS += $(OBJDIR)/sdf.o
OBJECTS += $(OBJDIR)/sfnt.o
OBJECTS += $(OBJDIR)/smooth.o
OBJECTS += $(OBJDIR)/spirv_cfg.o
OBJECTS += $(OBJDIR)/spirv_cpp.o
OBJECTS += $(OBJDIR)/spirv_cross.o
OBJECTS += $(OBJDIR)/spirv_cross_c.o
OBJECTS += $(OBJDIR)/spirv_cross_parsed_ir.o
OBJECTS += $(OBJDIR)/spirv_cross_util.o
OBJECTS += $(OBJDIR)/spirv_glsl.o
OBJECTS += $(OBJDIR)/spirv_hlsl.o
OBJECTS += $(OBJDIR)/spirv_msl.o
OBJECTS += $(OBJDIR)/spirv_parser.o
OBJECTS += $(OBJDIR)/spirv_reflect.o
OBJECTS += $(OBJDIR)/svg.o
OBJECTS += $(OBJDIR)/truetype.o
OBJECTS += $(OBJDIR)/type1.o
OBJECTS += $(OBJDIR)/type1cid.o
OBJECTS += $(OBJDIR)/type42.o
OBJECTS += $(OBJDIR)/utils.o
OBJECTS += $(OBJDIR)/ve_assets_manager.o
OBJECTS += $(OBJDIR)/ve_editor.o
OBJECTS += $(OBJDIR)/ve_editor_elements.o
OBJECTS += $(OBJDIR)/ve_engine.o
OBJECTS += $(OBJDIR)/ve_flecs_os_backend.o
OBJECTS += $(OBJDIR)/ve_font.o
OBJECTS += $(OBJDIR)/ve_generated_editor_file.o
OBJECTS += $(OBJDIR)/ve_generated_serialization_file.o
OBJECTS += $(OBJDIR)/ve_input.o
OBJECTS += $(OBJDIR)/ve_renderer.o
OBJECTS += $(OBJDIR)/ve_scene.o
OBJECTS += $(OBJDIR)/ve_scene_manager.o
OBJECTS += $(OBJDIR)/ve_serialization.o
OBJECTS += $(OBJDIR)/ve_systems.o
OBJECTS += $(OBJDIR)/ve_utils.o
OBJECTS += $(OBJDIR)/ve_win32_platform.o
OBJECTS += $(OBJDIR)/ve_win32_shared_library.o
OBJECTS += $(OBJDIR)/winfnt.o

endif

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking project
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning project
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(GENERATED)) del /s /q $(subst /,\\,$(GENERATED))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/entry_point.o: src/entry_point.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ve_generated_editor_file1.o: src/generated/ve_generated_editor_file.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ve_generated_serialization_file1.o: src/generated/ve_generated_serialization_file.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/register.o: src/register.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/systems.o: src/systems.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

ifeq ($(config),game_debug)
$(OBJDIR)/ve_editor.o: ../../VEngine/src/editor/ve_editor.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ve_editor_elements.o: ../../VEngine/src/editor/ve_editor_elements.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ve_generated_editor_file.o: ../../VEngine/src/generated/ve_generated_editor_file.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ve_generated_serialization_file.o: ../../VEngine/src/generated/ve_generated_serialization_file.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ve_flecs_os_backend.o: ../../VEngine/src/platform/ve_flecs_os_backend.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ve_win32_platform.o: ../../VEngine/src/platform/win32/ve_win32_platform.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ve_win32_shared_library.o: ../../VEngine/src/platform/win32/ve_win32_shared_library.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ve_scene.o: ../../VEngine/src/scenes/ve_scene.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ve_scene_manager.o: ../../VEngine/src/scenes/ve_scene_manager.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ve_systems.o: ../../VEngine/src/systems/ve_systems.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ve_serialization.o: ../../VEngine/src/utils/ve_serialization.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ve_utils.o: ../../VEngine/src/utils/ve_utils.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ve_assets_manager.o: ../../VEngine/src/ve_assets_manager.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ve_engine.o: ../../VEngine/src/ve_engine.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ve_font.o: ../../VEngine/src/ve_font.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ve_input.o: ../../VEngine/src/ve_input.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ve_renderer.o: ../../VEngine/src/ve_renderer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/spirv_cfg.o: ../../VEngine/third_party/SPIRV-Cross/spirv_cfg.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/spirv_cpp.o: ../../VEngine/third_party/SPIRV-Cross/spirv_cpp.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/spirv_cross.o: ../../VEngine/third_party/SPIRV-Cross/spirv_cross.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/spirv_cross_c.o: ../../VEngine/third_party/SPIRV-Cross/spirv_cross_c.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/spirv_cross_parsed_ir.o: ../../VEngine/third_party/SPIRV-Cross/spirv_cross_parsed_ir.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/spirv_cross_util.o: ../../VEngine/third_party/SPIRV-Cross/spirv_cross_util.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/spirv_glsl.o: ../../VEngine/third_party/SPIRV-Cross/spirv_glsl.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/spirv_hlsl.o: ../../VEngine/third_party/SPIRV-Cross/spirv_hlsl.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/spirv_msl.o: ../../VEngine/third_party/SPIRV-Cross/spirv_msl.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/spirv_parser.o: ../../VEngine/third_party/SPIRV-Cross/spirv_parser.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/spirv_reflect.o: ../../VEngine/third_party/SPIRV-Cross/spirv_reflect.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/flecs.o: ../../VEngine/third_party/flecs/distr/flecs.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/autofit.o: ../../VEngine/third_party/freetype/src/autofit/autofit.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftbase.o: ../../VEngine/third_party/freetype/src/base/ftbase.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftbbox.o: ../../VEngine/third_party/freetype/src/base/ftbbox.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftbdf.o: ../../VEngine/third_party/freetype/src/base/ftbdf.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftbitmap.o: ../../VEngine/third_party/freetype/src/base/ftbitmap.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftcid.o: ../../VEngine/third_party/freetype/src/base/ftcid.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftdebug.o: ../../VEngine/third_party/freetype/src/base/ftdebug.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftfstype.o: ../../VEngine/third_party/freetype/src/base/ftfstype.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftgasp.o: ../../VEngine/third_party/freetype/src/base/ftgasp.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftglyph.o: ../../VEngine/third_party/freetype/src/base/ftglyph.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftgxval.o: ../../VEngine/third_party/freetype/src/base/ftgxval.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftinit.o: ../../VEngine/third_party/freetype/src/base/ftinit.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftmm.o: ../../VEngine/third_party/freetype/src/base/ftmm.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftotval.o: ../../VEngine/third_party/freetype/src/base/ftotval.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftpatent.o: ../../VEngine/third_party/freetype/src/base/ftpatent.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftpfr.o: ../../VEngine/third_party/freetype/src/base/ftpfr.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftstroke.o: ../../VEngine/third_party/freetype/src/base/ftstroke.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftsynth.o: ../../VEngine/third_party/freetype/src/base/ftsynth.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftsystem.o: ../../VEngine/third_party/freetype/src/base/ftsystem.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/fttype1.o: ../../VEngine/third_party/freetype/src/base/fttype1.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftwinfnt.o: ../../VEngine/third_party/freetype/src/base/ftwinfnt.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/bdf.o: ../../VEngine/third_party/freetype/src/bdf/bdf.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftbzip2.o: ../../VEngine/third_party/freetype/src/bzip2/ftbzip2.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftcache.o: ../../VEngine/third_party/freetype/src/cache/ftcache.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/cff.o: ../../VEngine/third_party/freetype/src/cff/cff.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/type1cid.o: ../../VEngine/third_party/freetype/src/cid/type1cid.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftgzip.o: ../../VEngine/third_party/freetype/src/gzip/ftgzip.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftlzw.o: ../../VEngine/third_party/freetype/src/lzw/ftlzw.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pcf.o: ../../VEngine/third_party/freetype/src/pcf/pcf.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pfr.o: ../../VEngine/third_party/freetype/src/pfr/pfr.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/psaux.o: ../../VEngine/third_party/freetype/src/psaux/psaux.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pshinter.o: ../../VEngine/third_party/freetype/src/pshinter/pshinter.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/psnames.o: ../../VEngine/third_party/freetype/src/psnames/psnames.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/raster.o: ../../VEngine/third_party/freetype/src/raster/raster.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sdf.o: ../../VEngine/third_party/freetype/src/sdf/sdf.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sfnt.o: ../../VEngine/third_party/freetype/src/sfnt/sfnt.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/smooth.o: ../../VEngine/third_party/freetype/src/smooth/smooth.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/svg.o: ../../VEngine/third_party/freetype/src/svg/svg.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/truetype.o: ../../VEngine/third_party/freetype/src/truetype/truetype.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/type1.o: ../../VEngine/third_party/freetype/src/type1/type1.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/type42.o: ../../VEngine/third_party/freetype/src/type42/type42.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/winfnt.o: ../../VEngine/third_party/freetype/src/winfonts/winfnt.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/raudio.o: ../../VEngine/third_party/raylib/src/raudio.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rcore.o: ../../VEngine/third_party/raylib/src/rcore.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rmodels.o: ../../VEngine/third_party/raylib/src/rmodels.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rshapes.o: ../../VEngine/third_party/raylib/src/rshapes.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rtext.o: ../../VEngine/third_party/raylib/src/rtext.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rtextures.o: ../../VEngine/third_party/raylib/src/rtextures.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/utils.o: ../../VEngine/third_party/raylib/src/utils.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

else ifeq ($(config),game_release)
$(OBJDIR)/ve_editor.o: ../../VEngine/src/editor/ve_editor.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ve_editor_elements.o: ../../VEngine/src/editor/ve_editor_elements.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ve_generated_editor_file.o: ../../VEngine/src/generated/ve_generated_editor_file.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ve_generated_serialization_file.o: ../../VEngine/src/generated/ve_generated_serialization_file.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ve_flecs_os_backend.o: ../../VEngine/src/platform/ve_flecs_os_backend.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ve_win32_platform.o: ../../VEngine/src/platform/win32/ve_win32_platform.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ve_win32_shared_library.o: ../../VEngine/src/platform/win32/ve_win32_shared_library.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ve_scene.o: ../../VEngine/src/scenes/ve_scene.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ve_scene_manager.o: ../../VEngine/src/scenes/ve_scene_manager.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ve_systems.o: ../../VEngine/src/systems/ve_systems.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ve_serialization.o: ../../VEngine/src/utils/ve_serialization.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ve_utils.o: ../../VEngine/src/utils/ve_utils.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ve_assets_manager.o: ../../VEngine/src/ve_assets_manager.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ve_engine.o: ../../VEngine/src/ve_engine.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ve_font.o: ../../VEngine/src/ve_font.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ve_input.o: ../../VEngine/src/ve_input.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ve_renderer.o: ../../VEngine/src/ve_renderer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/spirv_cfg.o: ../../VEngine/third_party/SPIRV-Cross/spirv_cfg.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/spirv_cpp.o: ../../VEngine/third_party/SPIRV-Cross/spirv_cpp.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/spirv_cross.o: ../../VEngine/third_party/SPIRV-Cross/spirv_cross.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/spirv_cross_c.o: ../../VEngine/third_party/SPIRV-Cross/spirv_cross_c.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/spirv_cross_parsed_ir.o: ../../VEngine/third_party/SPIRV-Cross/spirv_cross_parsed_ir.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/spirv_cross_util.o: ../../VEngine/third_party/SPIRV-Cross/spirv_cross_util.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/spirv_glsl.o: ../../VEngine/third_party/SPIRV-Cross/spirv_glsl.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/spirv_hlsl.o: ../../VEngine/third_party/SPIRV-Cross/spirv_hlsl.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/spirv_msl.o: ../../VEngine/third_party/SPIRV-Cross/spirv_msl.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/spirv_parser.o: ../../VEngine/third_party/SPIRV-Cross/spirv_parser.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/spirv_reflect.o: ../../VEngine/third_party/SPIRV-Cross/spirv_reflect.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/flecs.o: ../../VEngine/third_party/flecs/distr/flecs.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/autofit.o: ../../VEngine/third_party/freetype/src/autofit/autofit.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftbase.o: ../../VEngine/third_party/freetype/src/base/ftbase.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftbbox.o: ../../VEngine/third_party/freetype/src/base/ftbbox.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftbdf.o: ../../VEngine/third_party/freetype/src/base/ftbdf.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftbitmap.o: ../../VEngine/third_party/freetype/src/base/ftbitmap.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftcid.o: ../../VEngine/third_party/freetype/src/base/ftcid.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftdebug.o: ../../VEngine/third_party/freetype/src/base/ftdebug.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftfstype.o: ../../VEngine/third_party/freetype/src/base/ftfstype.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftgasp.o: ../../VEngine/third_party/freetype/src/base/ftgasp.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftglyph.o: ../../VEngine/third_party/freetype/src/base/ftglyph.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftgxval.o: ../../VEngine/third_party/freetype/src/base/ftgxval.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftinit.o: ../../VEngine/third_party/freetype/src/base/ftinit.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftmm.o: ../../VEngine/third_party/freetype/src/base/ftmm.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftotval.o: ../../VEngine/third_party/freetype/src/base/ftotval.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftpatent.o: ../../VEngine/third_party/freetype/src/base/ftpatent.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftpfr.o: ../../VEngine/third_party/freetype/src/base/ftpfr.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftstroke.o: ../../VEngine/third_party/freetype/src/base/ftstroke.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftsynth.o: ../../VEngine/third_party/freetype/src/base/ftsynth.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftsystem.o: ../../VEngine/third_party/freetype/src/base/ftsystem.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/fttype1.o: ../../VEngine/third_party/freetype/src/base/fttype1.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftwinfnt.o: ../../VEngine/third_party/freetype/src/base/ftwinfnt.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/bdf.o: ../../VEngine/third_party/freetype/src/bdf/bdf.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftbzip2.o: ../../VEngine/third_party/freetype/src/bzip2/ftbzip2.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftcache.o: ../../VEngine/third_party/freetype/src/cache/ftcache.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/cff.o: ../../VEngine/third_party/freetype/src/cff/cff.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/type1cid.o: ../../VEngine/third_party/freetype/src/cid/type1cid.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftgzip.o: ../../VEngine/third_party/freetype/src/gzip/ftgzip.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftlzw.o: ../../VEngine/third_party/freetype/src/lzw/ftlzw.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pcf.o: ../../VEngine/third_party/freetype/src/pcf/pcf.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pfr.o: ../../VEngine/third_party/freetype/src/pfr/pfr.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/psaux.o: ../../VEngine/third_party/freetype/src/psaux/psaux.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pshinter.o: ../../VEngine/third_party/freetype/src/pshinter/pshinter.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/psnames.o: ../../VEngine/third_party/freetype/src/psnames/psnames.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/raster.o: ../../VEngine/third_party/freetype/src/raster/raster.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sdf.o: ../../VEngine/third_party/freetype/src/sdf/sdf.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sfnt.o: ../../VEngine/third_party/freetype/src/sfnt/sfnt.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/smooth.o: ../../VEngine/third_party/freetype/src/smooth/smooth.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/svg.o: ../../VEngine/third_party/freetype/src/svg/svg.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/truetype.o: ../../VEngine/third_party/freetype/src/truetype/truetype.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/type1.o: ../../VEngine/third_party/freetype/src/type1/type1.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/type42.o: ../../VEngine/third_party/freetype/src/type42/type42.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/winfnt.o: ../../VEngine/third_party/freetype/src/winfonts/winfnt.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/raudio.o: ../../VEngine/third_party/raylib/src/raudio.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rcore.o: ../../VEngine/third_party/raylib/src/rcore.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rmodels.o: ../../VEngine/third_party/raylib/src/rmodels.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rshapes.o: ../../VEngine/third_party/raylib/src/rshapes.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rtext.o: ../../VEngine/third_party/raylib/src/rtext.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rtextures.o: ../../VEngine/third_party/raylib/src/rtextures.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/utils.o: ../../VEngine/third_party/raylib/src/utils.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

endif

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif